
services:
  db:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: postgres

    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
volumes:
  db-data:
