CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE users (
    id bigserial PRIMARY KEY,
    email citext UNIQUE NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);